name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  lint:
    build:
      steps:
	   - name: Super-Linter
	   - uses: actions/checkout@v2
             uses: github/super-linter@v4.9.5
             env: 
	       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
